<?php

namespace AppleSignInTest\Unit;

use AppleSignIn\Payload;
use PHPUnit\Framework\TestCase;

/**
 * Class PayloadTest
 * @package AppleSignInTest\Unit
 */
class PayloadTest extends TestCase
{
    /** @var \stdClass */
    private $jwtPayload;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->jwtPayload = new \stdClass();
        $this->jwtPayload->sub = 'some-user-uuid-string';
        $this->jwtPayload->email = 'user@example.com';
    }

    public function testGetUserUUIDReturnsSubClaim()
    {
        $payload = new Payload($this->jwtPayload);

        $this->assertEquals('some-user-uuid-string', $payload->getUserUUID());
    }

    public function testGetEmailReturnsEmailClaim()
    {
        $payload = new Payload($this->jwtPayload);

        $this->assertEquals('user@example.com', $payload->getEmail());
    }
}
